### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by Bleedblood**
Attempted Merge

### CODE REVIEW

**Comment by Bleedblood** [comment]
I'm not 100% but I think you have to approve the merge. I may not have the permissions, or I may just not know where to look.

**Comment by thomassw66** [comment]
You made the master branch gabe, there's no way you don't have permissions.

**Comment by thomassw66** [comment]
We need to get everyone to start submitting their shit to the github.

**Comment by GabrielFabian** [comment]
This issue is resolved, disregard.

**Comment by GabrielFabian** [comment]
Yeah man, I'm actually hitting everyone up about it right now.

**Comment by thomassw66** [comment]
Ok cool. Send them a tutorial link if they can't figure it out.

http://rogerdudler.github.io/git-guide/

**Comment by thomassw66** [comment]
I really want to see what progress they have made on the map and player
because we can't help them with that until we see what they've already done.

**Comment by Bobalo317** [comment]
I dont have the map, but I got the player to spawn, shoot and move. The
zombies spawn randomly around the top and bottom of the map at start. The
bullets have hit detection and if the player runs into the zombie he dies.

**Comment by GabrielFabian** [comment]
Just sent out a message on FB asking that everyone keeps their own work on
seperate branches so we don't detonate the master.

**Comment by GabrielFabian** [comment]
Fuck yeah Randel, nice work.

**Comment by Bobalo317** [comment]
Did everyone else get the message, I think I just sent it to you. If you
want I can bring it to class. I still need to figure out how to put it on
git.

**Comment by thomassw66** [comment]
Guys will someone send me the timely file, I want to start working on the
map and zombie following algorithm.

**Comment by thomassw66** [comment]
tilemap**

**Comment by thomassw66** [comment]
Or put it on github we need to have everything up there

**Comment by thomassw66** [comment]
Nevermind about the tilemap I found it.

**Pull request merged**
